management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: basketball-matching

    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

      slo:
        "[http.server.requests]":
          - 100ms
          - 300ms
          - 500ms
          - 1s
          - 3s

spring:
  jpa:
    show-sql: false
    open-in-view: false

    properties:
      hibernate:
        format_sql: false

        session_factory:
          statement_inspector: com.example.basketballmatching.global.monitoring.query.QueryCountInspector
app:
  monitoring:
    query-count:
      enabled: true


logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    com.example.basketballmatching.game.service.GameService: WARN
    com.example.basketballmatching.game.service.GameParticipantService: WARN
